spring.application.name=jwt-security-demo
# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# A secure key for signing JWT tokens. In production, use a long, random key.
token.signing.key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351