package com.misbah.dtodemo.service;
import com.misbah.dtodemo.dto.UserDto;
import com.misbah.dtodemo.entity.User;
import com.misbah.dtodemo.mapper.UserMapper;
import com.misbah.dtodemo.repository.UserRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class UserServiceImpl implements UserService
{
    private final UserRepository userRepository;

    public UserServiceImpl(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

//    @Override
//    public UserDto createUser(UserDto userDto, String password) {
//        User user= UserMapper.toEntity(userDto,password);
//        return UserMapper.toDto(userRepository.save(user));
//    }

    @Override
    public UserDto createUser(UserDto dto,String password)
    {
//        we have to do 3 things
//        1.convert the given userDto into user entity via the Mapper method
//        Inside UserMapper class the mapper method takes the user object and attaches the password to it
//        and creates the User Entity object via the Lombok's builder method
//        2.after it has been converted to User entity save it in DB using UserRepository
//        Thus the entire User Entity id(generated by JPA),name ,email and pw given by User is inside the User object and saved to DB
//        3.Then Convert the saved User object into a UserDto again to send back to the Controller Layer
//        this UserDto object will contain everything but the password
//        4.
        User user=UserMapper.toEntity(dto,password);
        User saved=userRepository.save(user);
        return UserMapper.toDto(saved);
    }

    @Override
    public List<UserDto> getAllUsers() {
        return userRepository.findAll()
                .stream()
                .map(UserMapper::toDto)
                .toList();
    }
}
